import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Coders Hunt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navigation}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blogs</li>
        </ul>
      </nav>
      <div className={styles.main}>
        <h1 className={styles.heading}>Coder's Hunt</h1>
      </div>
      <div className={styles.blogs}>
        <h4 className={styles.small_heading}>Amazing Blogs for Coders by Hunting Coder.</h4>
      </div>
      <div className={styles.blog_section}>
        <h5 className={styles.blog_heading}>
         Javascript in 2023?</h5>
        <p className={styles.blog_content}>
        &rarr;  Javascript is amazing langauge of Web, Which can help you build amazing web application,
        <br/>
        </p>
        <p className={styles.spaning}>&rarr;  Javascript is amazing langauge of Web, Which can help you build amazing web application</p>
      </div>
      <div className={styles.blog_section}>
        <h5 className={styles.blog_heading}>
         Javascript in 2023?</h5>
        <p className={styles.blog_content}>
        &rarr;  Javascript is amazing langauge of Web, Which can help you build amazing web application,
        <br/>
        </p>
        <p className={styles.spaning}>&rarr;  Javascript is amazing langauge of Web, Which can help you build amazing web application</p>
      </div>
      <div className={styles.blog_section}>
        <h5 className={styles.blog_heading}>
         Javascript in 2023?</h5>
        <p className={styles.blog_content}>
        &rarr;  Javascript is amazing langauge of Web, Which can help you build amazing web application,
        <br/>
        </p>
        <p className={styles.spaning}>&rarr;  Javascript is amazing langauge of Web, Which can help you build amazing web application</p>
      </div>
    </>
  )
}
